fos_rest:
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: false
  body_converter:
    enabled: true
    validation_errors_argument: validationErrors
  body_listener:
    enabled: true
  serializer:
    serialize_null: true
  view:
    view_response_listener:  true
    serialize_null: true

  format_listener:
    enabled: true
    rules:
      - { path: ^/, fallback_format: json, priorities: ['json'] }
